spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: DEMOINTERN
    password: DEMOINTERN
    type: com.zaxxer.hikari.HikariDataSource

server:
  port: 8084